[package]
name = "mjpeg_test"
version = "0.1.0"
authors = ["Daisuke Kato"]
edition = "2018"

[dependencies]
actix-rt = "0.2"
actix-web = "1.0"
env_logger = "0.6"
futures = "0.1"
tokio = "0.1"

image = "0.22"
rand = "0.7"
